# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: 'mirror repo'
        script:
          - |
            set -euf -o pipefail;
            # clone it as a mirror
            git clone --mirror $BITBUCKET_GIT_SSH_ORIGIN ./mirrored;
            cd ./mirrored;
            git fetch -p origin;

            # target the new location
            git remote set-url --push origin https://airtonix:$GITHUB_PERSONAL_ACCESS_TOKEN@github.com/airtonix/$BITBUCKET_REPO_SLUG;

            # replicate
            git push --mirror;
